Traceback (most recent call last):
  File "runner.py", line 34, in <module>
    for tupla in scores:
  File "runner.py", line 12, in main
    # Perform preprocessing
  File "/home/u15089/dimmy/d2v/doc2vec-driven-sentiment-analysis-of-imdb-reviews/data_prep.py", line 132, in prepare_data
    X_train, X_test, unlab_reviews = preparer.clean_reviews(X_train, X_test, unlab_reviews)
  File "/home/u15089/dimmy/d2v/doc2vec-driven-sentiment-analysis-of-imdb-reviews/data_prep.py", line 90, in clean_reviews
    X_train = self.cleaner(X_train, full_clean=True)
  File "/home/u15089/dimmy/d2v/doc2vec-driven-sentiment-analysis-of-imdb-reviews/data_prep.py", line 65, in cleaner
    corpus = [self.remove_non_ascii(review) for review in corpus]
  File "/home/u15089/dimmy/d2v/doc2vec-driven-sentiment-analysis-of-imdb-reviews/data_prep.py", line 65, in <listcomp>
    corpus = [self.remove_non_ascii(review) for review in corpus]
  File "/home/u15089/dimmy/d2v/doc2vec-driven-sentiment-analysis-of-imdb-reviews/data_prep.py", line 57, in remove_non_ascii
    return unidecode(unicode(text, encoding = "utf-8"))
NameError: name 'unicode' is not defined
